version: '3.9'
services:
  product:
    build: ./product
    container_name: ecomm-product
    ports:
      - "3002:3002"

  account:
    build: ./account
    container_name: ecomm-account
    ports:
      - "3002:3002"

  mongodb:
    container_name: mongo-ecomm
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - "27017:27017"