version: '3.9'
services:      
  mongodb:
    container_name: mongo-bilro
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=bilro
      - MONGO_INITDB_ROOT_PASSWORD=8NV7wAzE5T0o28Zp
    ports:
     - "27017:27017"
    command: mongod --bind_ip=0.0.0.0
    volumes:
      - /data/db:/data/db
  