version: '3.9'
services:      
  mongodb:
    container_name: mongo-bilro
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
     - "27017:27017"
    command: mongod --bind_ip=0.0.0.0
    volumes:
      - /data/db:/data/db
  mysql:
    container_name: mysql-bilro
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: bilro-finance
    ports:
      - 3306:3306
    volumes:
      - /data/mysql:/var/lib/mysql