openapi: 3.0.3
info:
  title: API de produtos
  description: API para controlar produtos do sistema Ecomm
  version: 0.0.1
externalDocs:
  description: Link do GitHub
  url: https://github.com/anavsky/ecomm
servers: 
- url: https://63d16adc3f08e4a8ff977c0e.mockapi.io/api/
  description: API de teste
paths:
  /categories:
    get:
      summary: Lista todas as categorias
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    nome:
                      type: string
                    status:
                      type: string
                minItems: 1
        204:
          description: Não há categorias cadastradas
        404:
          description: Categoria não encontrada
          content:
            application/json:
              example: "Nenhuma categoria correspondente encontrada"
        500:
          description: Erro interno
          content:
            application/json:
              example: "Erro interno"
  /categories/{id}:
    get:
      summary: Recupera uma categoria pelo id
      parameters: 
      - name: id
        in: path
        schema:
          type: integer
        required: true
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    nome:
                      type: string
                    status:
                      type: string