openapi: 3.0.3
info:
  title: API de produtos
  description: API para controlar produtos do sistema Ecomm
  version: 0.0.1
externalDocs:
  description: Link do GitHub
  url: https://github.com/anavsky/ecomm
servers: 
- url: https://63d16adc3f08e4a8ff977c0e.mockapi.io/api/
  description: API de teste
paths:
  /categories:
    get:
      tags:
      - /categories
      summary: Lista todas as categorias
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Categories"
  /categories/{id}:
    get:
      tags:
      - /categories
      summary: Recupera uma categoria pelo id
      parameters: 
      - name: id
        in: path
        schema:
          type: integer
        required: true
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Category"
        404:
          $ref: '#/components/responses/NotFound'
  /admin/categories:
    post:
      tags:
      - /admin/categories
      security:
      - auth: []
      summary: Insere nova categoria
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
      responses:
        201:
          $ref: "#/components/responses/Success"
        401:
          $ref: '#/components/responses/UnauthorizedError'
  /admin/categories/{id}:
    parameters:
      - name: id
        in: path
        schema:
          type: integer
        required: true
    put:
      tags:
      - /admin/categories
      summary: Altera uma categoria pelo id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Category'
      
      responses:
        200:
          $ref: "#/components/responses/Success"
        401:
          $ref: '#/components/responses/UnauthorizedError'
        404:
          $ref: '#/components/responses/NotFound'
    patch:
      summary: Altera o status de uma categoria
      responses:
        200:
          description: Categoria foi alterada
        401:
          $ref: '#/components/responses/UnauthorizedError'
        404:
          $ref: '#/components/responses/NotFound'
    delete:
      tags:
      - /admin/categories
      summary: Apaga categoria pelo id
      responses:
        200:
          description: Categoria foi deletada
        401:
          $ref: '#/components/responses/UnauthorizedError'
        404:
          $ref: '#/components/responses/NotFound'
components:
  schemas:
    Category:
      type: object
      properties:
        id:
          type: integer
        nome:
          type: string
        status:
          type: string
    Categories:
      type: array
      items:
        $ref: "#/components/schemas/Category"
  securitySchemes:
    auth:
      type: http
      scheme: bearer
  responses:
    Success:
      description: "Sucesso"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Category"
    UnauthorizedError:
      description: "Requisição não autorizada"
      content:
        application/json:
          example: "Não autorizado"
    NotFound:
      description: Categoria não encontrada
      content:
        application/json:
          example: "Nenhuma categoria correspondente encontrada"
          
        